name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install src dependencies
      run: dotnet restore src/FakeXrmEasy.Core.csproj

    - name: Build src proj
      run: dotnet build src/FakeXrmEasy.Core.csproj --configuration Debug --no-restore

    - name: Install test dependencies
      run: dotnet restore tests/FakeXrmEasy.Core.Tests.csproj

    - name: Build test proj
      run: dotnet build tests/FakeXrmEasy.Core.Tests.csproj --configuration Debug --no-restore
  
    - name: Test
      run: dotnet test tests/FakeXrmEasy.Core.Tests.csproj --configuration Debug --no-restore --verbosity normal
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
